### ISSUE TITLE
Document not compiling due to change in tagpdf package

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/sa4ss#10]
The [tagpdf](https://github.com/u-fischer/tagpdf) package on github was updated yesterday which appears to be causing an error during compiling of the document.  I get the following error: 

! Package tagpdf Error: PDF resource management is no active!
(tagpdf)                tagpdf will no work..

which I have tracked down to this [function line 42](https://github.com/u-fischer/tagpdf/blob/70371fa9c4e8a1921c7f6d45276c325ca7a038f2/source/dtx/tagpdf.dtx) in the package.  I attempted to comment out the package in the sa4ss.sty file to get around this issue for a moment but it appears that I am not commenting out all the needed lines or just the correct ones because I then receive a different error about the toplevel hook which may be using this package for tags:

! Undefined control sequence.
\__hook_toplevel begindocument ->\tagstructbegin 
                                                 {tag=Document}

I am unsure how to work around or fix this issue at the moment.

**Comment by kellijohnson-NOAA** [comment]
From tagpdf ... Version 0.80 is a major extension of the package with a number of breaking changes. 

The package
- requires the new PDF management code from the pdfmanagement-testphase bundle
- requires utf8 encoding 
- requires a latex 2020-10-01 or newer and a L3 programming layer  2021-02-18 or newer
- changed the module name prefix from uftag to tag
- adds support for associated files issue #18
- add support for /Lang, /Ref and /E. (issue #22)

I will look.

**Comment by kellijohnson-NOAA** [comment]
I was able to recreate your error on my machine that has tinytex installed. Tinytex automatically updates ctan packages where miktex doesn't. There was a message printed to the screen during package updates that "tagpdf Error: PDF resource management is no active! tagpdf will no work.." I will work on how to install PDF resource management which I found on github [here](https://github.com/latex3/pdfresources).

**Comment by kellijohnson-NOAA** [comment]
I am excited to report that Adobe recently provided the LaTeX community with funding to do research on making ALL future pdfs built from .tex files compliant with respect to ADA issues. This is a long-term project that has a six-year completion timeline. Part of the backwards compatibility issue with the upgrade to tagpdf was because of their work towards meeting these goals. So, the work is in our favour though it is a bit of a pain for the short term. I have made significant headway in fixing sa4ss to work with the newest version of sa4ss but I will be unable to finish by the EOD b/c of additional issues I am running into with fonts. I see the font problems as trivial book-keeping tasks and I will work on them this weekend. Thank you for your patience as we work through the growing pains of switching from word.

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa can you test it out for me?

**Comment by chantelwetzel-noaa** [comment]
I updated sa4ss and attempted to create and compile a test assessment: I received the following error in the R terminal:

"C:/Users/CHANTE~1.WET/AppData/Local/Pandoc/pandoc" +RTS -K512m -RTS _main.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output _main.tex --lua-filter "C:\PROGRA~1\R\R-40~1.1\library\bookdown\RMARKD~1\lua\CUSTOM~1.LUA" --lua-filter "C:\PROGRA~1\R\R-40~1.1\library\RMARKD~1\RMARKD~1\lua\PAGEBR~1.LUA" --lua-filter "C:\PROGRA~1\R\R-40~1.1\library\RMARKD~1\RMARKD~1\lua\LATEX-~1.LUA" --self-contained --table-of-contents --toc-depth 2 --template "C:\PROGRA~1\R\R-40~1.1\library\sa4ss\RMARKD~1\TEMPLA~1\sa\RESOUR~1\sadraft.tex" --number-sections --highlight-style tango --pdf-engine lualatex --top-level-division=section --wrap=none --default-image-extension=png --lua-filter=tagged-filter.lua --variable tables=yes --standalone -Mhas-frontmatter=false --filter "C:/Users/CHANTE~1.WET/AppData/Local/Pandoc/pandoc-citeproc.exe" 
tlmgr.pl: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (verified)
[1/1, ??:??/??:??] install: pdfmanagement-testphase [37k]
running mktexlsr ...
done running mktexlsr.
tlmgr.pl: package log updated: C:/Users/Chantel.Wetzel/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr.log
! Undefined control sequence.
<recently read> \pdfmanagement 

Here is the information from the end of the log:

Inserting `luaotfload.rewrite_fontname' at position 6 in `luaotfload.patch_font'
. L3 programming layer <2021-02-18> (./input_accessability.tex
(c:/Users/Chantel.Wetzel/AppData/Roaming/TinyTeX/texmf-dist/tex/latex/pdfmanage
ment-testphase/pdfmanagement-testphase.sty
Package: pdfmanagement-testphase 2021-02-22 v0.95a LaTeX PDF management testphas
e bundle

(c:/Users/Chantel.Wetzel/AppData/Roaming/TinyTeX/texmf-dist/tex/latex/pdfmanage
ment-testphase/pdfmanagement-testphase.ltx
File: pdfmanagement-testphase.ltx 2021-02-22 v0.95a PDF management code (testpha
se)

LaTeX3 Info: Defining command \DeclareDocumentMetadata with sig. 'm' on line
(LaTeX3)     961.


LaTeX3 Info: Defining command \AddToDocumentProperties with sig. 'O{\@currname
(LaTeX3)     }mm' on line 971.


LaTeX3 Info: Defining command \GetDocumentProperties with sig. 'm' on line
(LaTeX3)     975.


LaTeX3 Info: Defining command \ShowDocumentProperties with sig. '' on line
(LaTeX3)     987.


(c:/Users/Chantel.Wetzel/AppData/Roaming/TinyTeX/texmf-dist/tex/latex/l3experim
ental/l3bitset/l3bitset.sty
Package: l3bitset 2021-02-18 L3 Experimental bitset support
\l__bitset_internal_int=\count175
)))
(c:/Users/Chantel.Wetzel/AppData/Roaming/TinyTeX/texmf-dist/tex/latex/l3kernel/
expl3.sty
Package: expl3 2021-02-18 L3 programming layer (loader) 

(c:/Users/Chantel.Wetzel/AppData/Roaming/TinyTeX/texmf-dist/tex/latex/l3kernel/
l3debug.def
File: l3debug.def 2019-04-06 L3 Debugging support
)
(c:/Users/Chantel.Wetzel/AppData/Roaming/TinyTeX/texmf-dist/tex/latex/l3backend
/l3backend-luatex.def
File: l3backend-luatex.def 2021-02-18 L3 backend support: PDF output (LuaTeX)
\l__color_backend_stack_int=\count176
\l__pdf_internal_box=\box47
))
(c:/Users/Chantel.Wetzel/AppData/Roaming/TinyTeX/texmf-dist/tex/latex/pdfmanage
ment-testphase/l3backend-testphase-luatex.def
File: l3backend-testphase-luatex.def 2021-02-22 LaTeX PDF management testphase b
undle backend support:PDFoutput(LuaTeX)

(c:/Users/Chantel.Wetzel/AppData/Roaming/TinyTeX/texmf-dist/tex/latex/pdfmanage
ment-testphase/l3ref-tmp.sty
Package: l3ref-tmp 2020-10-09 L3 Experimental cross-referencing
)
\l__pdf_backend_tmpa_box=\box48
\g__pdf_backend_resourceid_int=\count177
\g__pdf_backend_name_int=\count178
\g__pdf_backend_page_int=\count179
\g__pdf_backend_EmbeddedFiles_int=\count180
)

LaTeX3 Info: Redefining command \DeclareDocumentMetadata with sig. 'm' on line
(LaTeX3)     3.


(c:/Users/Chantel.Wetzel/AppData/Roaming/TinyTeX/texmf-dist/tex/latex/pdfmanage
ment-testphase/pdfmanagement-firstaid.sty
Package: pdfmanagement-firstaid 2021-02-22 v0.95a LaTeX PDF management testphase
 bundle / firstaid-patches

Package pdfmanagement Info: loading pdfmanagement firstaid code for pgf

)
! Undefined control sequence.
<recently read> \pdfmanagement 
               
l.4 \pdfmanagement
                _add:nnn{Catalog}{Lang}{(enUS)}

**Comment by iantaylor-NOAA** [comment]
For what it's worth, the following worked for me, where the tagpdf folder in the tinytex library on my machine is showing that it was updated today, so presumably the current version:
```
> remotes::install_github("nwfsc-assess/sa4ss")
> sa4ss::draft(authors = "Kelli F. Johnson", create_dir = TRUE)
> setwd("doc")
> bookdown::render_book("00a.Rmd", clean = FALSE, output_dir = getwd())
```
The output was as follows:
```
processing file: _main.Rmd
  |..............                                                        |  20%
   inline R code fragments

  |............................                                          |  40%
label: opts (with options) 
List of 1
 $ include: logi FALSE

  |..........................................                            |  60%
  ordinary text without R code

  |........................................................              |  80%
label: executive (with options) 
List of 1
 $ echo: logi FALSE

  |......................................................................| 100%
   inline R code fragments


output file: _main.knit.md

"C:/Users/IAN~1.TAY/AppData/Local/Pandoc/pandoc" +RTS -K512m -RTS _main.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output _main.tex --lua-filter "C:\~\R\R-4.0.2\library\bookdown\rmarkdown\lua\custom-environment.lua" --lua-filter "C:\~\R\R-4.0.2\library\rmarkdown\rmarkdown\lua\pagebreak.lua" --lua-filter "C:\~\R\R-4.0.2\library\rmarkdown\rmarkdown\lua\latex-div.lua" --self-contained --table-of-contents --toc-depth 2 --template "C:\~\R\R-4.0.2\library\sa4ss\rmarkdown\templates\sa\resources\sadraft.tex" --number-sections --highlight-style tango --pdf-engine lualatex --top-level-division=section --wrap=none --default-image-extension=png --lua-filter=tagged-filter.lua --variable tables=yes --standalone -Mhas-frontmatter=false --filter "C:/Users/IAN~1.TAY/AppData/Local/Pandoc/pandoc-citeproc.exe" 

tlmgr.pl: package repository https://mirrors.concertpass.com/tex-archive/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr.pl install: package already present: pdfmanagement-testphase
tlmgr.pl: package repository https://mirrors.concertpass.com/tex-archive/systems/texlive/tlnet (not verified: gpg unavailable)
[1/1, ??:??/??:??] install: luatex85 [2k]
running mktexlsr ...
done running mktexlsr.
tlmgr.pl: package log updated: C:/Users/ian.taylor/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr.log

Output created: _main.pdf
[1] "C:/~/doc/_main.pdf"
Warning message:
In has_crop_tools() : 
Tool(s) not installed or not in PATH: pdfcrop, ghostcript
-> As a result, figure cropping will be disabled.
```

**Comment by kellijohnson-NOAA** [comment]
Thanks @chantelwetzel-noaa and @iantaylor-NOAA for doing the testing, hopefully I will get the automated testing up and running better so that this process will become easier. The has_crop_tools() message is a new one. I will have to investigate where that one is coming from.

**Comment by kellijohnson-NOAA** [comment]
Found it, rmarkdown internal code. @iantaylor-NOAA do you have time to run the following and provide the output?
```
is_osx <- function() {
  Sys.info()["sysname"] == "Darwin"
}
find_program <- function(program) {
  if (is_osx()) {
    res <- suppressWarnings({
      # Quote the path (so it can contain spaces, etc.) and escape any quotes
      # and escapes in the path itself
      sanitized_path <- gsub("\\", "\\\\", Sys.getenv("PATH"), fixed = TRUE)
      sanitized_path <- gsub("\"", "\\\"", sanitized_path, fixed = TRUE)
      system(paste0("PATH=\"", sanitized_path, "\" /usr/bin/which ", program),
             intern = TRUE)
    })
    if (length(res) == 0)
      ""
    else
      res
  } else {
    Sys.which(program)
  }
}
has_crop_tools <- function() {
  tools <- c(
    pdfcrop = unname(find_program("pdfcrop")),
    ghostscript = unname(tools::find_gs_cmd())
  )
  missing <- tools[tools == ""]
  if (length(missing) == 0) return(TRUE)
  x <- paste0(names(missing), collapse = ", ")
  warning(
    sprintf("\nTool(s) not installed or not in PATH: %s", x),
    "\n-> As a result, figure cropping will be disabled."
  )
  FALSE
}
has_crop_tools()
```

**Comment by iantaylor-NOAA** [comment]
This is the output:
```
[1] FALSE
Warning message:
In has_crop_tools() : 
Tool(s) not installed or not in PATH: pdfcrop, ghostscript
-> As a result, figure cropping will be disabled.
```

**Comment by chantelwetzel-noaa** [comment]
I was able to compile an existing sa4ss document by just copying over the input_accessability.tex file!  So, for anyone with an existing sa4ss document you should:

1. Update the sa4ss package
2. Load package in your R session
3. Create a dummy "test" folder somewhere on your computer and set the working directory to navigate to this folder.
4. Run the draft function.
5. Copy the input_accessibility.tex file created from the draft function over to your existing document directory.  

Did I miss any step @kellijohnson-NOAA ?

**Comment by kellijohnson-NOAA** [comment]
Great, thanks @chantelwetzel-noaa for testing it out. Given that you have already tested that it works, future users could just grab input_accessibility.tex from the sass folder in their R library for example mine is here, C:\Program Files\R\library\sa4ss\rmarkdown\templates\sa\skeleton\input_accessibility.tex, or from the skeleton folder if they have the git repo cloned. Either way will work.

**Comment by kellijohnson-NOAA** [comment]
I am happy to report that the github actions present in this repository now compile the same test version of the pdf that @chantelwetzel-noaa mentions above and saves the pdf for viewing in the bookdown [actions folder](https://github.com/nwfsc-assess/sa4ss/actions/). I don't think anyone other than the data-moderate team has actually started to use this package, so I am assuming that @brianlangseth-NOAA is also aware of the above instructions on how to retrofit an old document so I am closing this issue. Great job team on working together to get the data-moderate assessments back online and making the package better.
