### ISSUE TITLE
pandoc installation

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/sa4ss#12]
Thank you to @kellijohnson-NOAA for adding to the ReadMe to help with installation. One item that is not addressed there is the installation of pandoc.  I think I remember needing to install this on my machine since I am not working in Rstudio but I am not 100% if this was a required step.  If so we should add some information about what type of user would need to have pandoc installed (R terminal vs Rstudio users), how to check if pandoc is installed on your machine (cmd pandoc --version), and the correct steps for installation if needed.  I am happy to try to add this information but wanted to check to see if this is something that most people would need to do.

**Comment by kellijohnson-NOAA** [comment]
This [website](https://alexd106.github.io/intro2R/install_rmarkdown.html#:~:text=The%20R%20companion%20package%20tinytex,R%20Markdown%20documents%20to%20PDF.&text=With%20the%20rmarkdown%20package%2C%20RStudio,compile%20most%20R%20Markdown%20documents.) says that you will need to install pandoc if you don't have Rstudio. I think IT installs Rstudio by default unless you are weird like me and ask to NOT have it on your machine, so everyone should have it.
We should still make a check and have instructions though. Great idea.

**Comment by chantelwetzel-noaa** [comment]
Steps for pandoc check (notes from discussion with Ian, Kelli, and Jason):

- Rterminal - Check for pandoc being available in the R terminal by calling rmarkdown::pandoc_available()  If you get a FALSE in return this could mean that pandoc is either not installed or not available in your PATH.  If you have Rstudio installed on your machine check to see if pandoc is available there.
- Open Rstudio and type rmarkdown::pandoc_available() in the terminal window.  Hopefully the answer here is TRUE which means you may only need to add it to your PATH.
- Check that pandoc is available in your PATH by opening the command prompt window and typing PATH
- If it is not in your path you can add it by 1) start menu, 2) type environment, 3) select "edit environmental variables for your account"
- Determine where pandoc lives by rmarkdown::pandoc_exec() 
- Add this location to your path inside the "Edit environmental variable for your account"
- Now return to the command line enter "path" and confirm that pandoc is now available in your path

Pandoc is available within RStudio, so if Rstudio is installed on your machine you should not have to separately install pandoc but may have to take the above steps to ensure that it is available in your PATH.

**Comment by iantaylor-NOAA** [comment]
Thanks @chantelwetzel-noaa.
In the last step on your list, if you return to the same command line window, I don't think it will be aware of the updates to your path. You need to open a new command window. Likewise rmarkdown::pandoc_available() may not see the updates to your path if the R terminal was already open, but opening a new R terminal should allow it to see the updates.

**Comment by kellijohnson-NOAA** [comment]
I just updated pandoc today on one of my machines ... which led to the new function session_test() returning an informative error message for me. 
```
pandoc-citeproc filter. Use --citeproc instead
```
So, we will need to find a way forward so that both versions of pandoc work. I wonder what version @shcaba has installed?

**Comment by chantelwetzel-noaa** [comment]
I have pandoc version 2.10 and I think @shcaba had a slightly newer version (2.11?).  What revision to the template would be required for the newer versions of pandoc?

**Comment by kellijohnson-NOAA** [comment]
I just upgraded to 2.11.4. They stopped the use of an argument 
```
This package is no longer maintained. Pandoc now uses the citeproc library, and no external filter is needed.
```
So, it is for the better I think but leads to a lack of backwards-compatible code.
