### ISSUE TITLE
inputenc and hyperxmp warnings for sa4ss documents created before accessibility updates 

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/sa4ss#13]
For my existing documents, created prior to the new accessibility updates, I am able to compile the document but I am getting two warnings that I did not receive for the test document created from the updated package.  

The first warning is for the inputenc package:

`Package inputenc Warning: inputenc package ignored with utf8 based engines.`

The second warning is for the hyperxmp package:

`Package hyperxmp Warning: Suppressing the _entire_ PDF Info dictionary.
(hyperxmp)                Please notify the hyperxmp maintainer.`

I was able to eliminate both of these warnings by making some minor changes sa4ss.sty based on the updated sty file.  If users encounter either of these warnings they can be addressed by making the following edits to the sty file:

- inputenc: in the sa4ss.sty file remove  the following line:
`\RequirePackage[utf8]{inputenc}`

-hyperxmp: in the sa4ss.sty file remove the following line:
`\usepackage{hyperxmp}`

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa thanks for noting these, and yes the two packages don't play nice with the updates to tagpdf. I think that the larger question here though is, how do we find a sustainable way forward that users can update their sty file when the package is updated without breaking their existing code. Do you ever touch the .sty file for things specific to your document? It could be that we just make a helper function that updates the sty file in your directory. And, if other files are updated we can think about how to handle those later. I can't expect everyone to copy and paste stuff though each time we make tweaks, like what I made you do. Do you have any ideas?

**Comment by chantelwetzel-noaa** [comment]
I have tried to avoid making any changes to the sty file but I have made 3 edits. One of these we (or actually I) should add it to the template but the other two are workarounds for issues I have encountered and we may want to determine if there are better ways to deal with them.

Edits:
1) Add the Hook and Line survey to the acronym list:
`\newacronym{s-hkl}{Hook and Line Survey}{\glsentrytext{nwfsc} Hook and Line Survey}`

2) I was encountering an error about [consecutive dead cycles](https://tex.stackexchange.com/questions/409796/todonotes-output-loop-100-consecutive-dead-cycles-after-50-todo-on-a-page) which appeared to be related to the number of figures and tables in the document.  I fixed this by adding the following line:
`\maxdeadcycles=200`

3) The final error I was encountering was also due to the excessive numbers of figures and tables where I ran out of floats.  I fixed this in a similar fashion as above by adding the following line:
`\extrafloats{200}`

I doubt there are many people who would be comfortable editing the sty file but in case there were minor tweaks similar to the ones described above I think a helper function that could edit specific lines which could be built upon as other things change may be the best approach to assisting user in maintaining the sty file.

**Comment by kellijohnson-NOAA** [comment]
First, yes if you could add the acronym that would be EXCELLENT. Second, thank you so much for starting this issue, it has generated lots of development ideas in my head that would not have come up if I was left to think alone.
I think in the future it would be best to have the acronym list as a separate file. Though, I probably won't make that change this year.
Regarding how to update the sty file, I don't know of a way in R to do what you are suggesting b/c there is no way to know what the line numbers would be given user might have their own edits. BUT, git can do this for you :) Maybe, we just need a disclaimer at the top of the sty file for users to NOT edit it and if they do so then they run the risk of conflicts? Or, is this too harsh?

**Comment by chantelwetzel-noaa** [comment]
I don't think that would be too harsh.  Ideally, if people find the need to edit the sty file, then it would best to encourage them to propose their edits to the template.  This approach might encourage people to take this approach out of fear alone!

**Comment by kellijohnson-NOAA** [comment]
Closing this issue b/c warnings are fixed and outstanding tasks for floats are part of #24.
