### ISSUE TITLE
Incorporating text on the same page with tables

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/sa4ss#17]
As I have begun to work on the executive summary I have noticed an issue where pages with tables won't include any text.  I am not having this issue with pages with text and figures.  I suspect it is related to some setting I have specified (e.g. clearpage with tables) but I am a little uncertain as to what.  I am currently adding tables to this section using the LaTeX \include command. Thought I would throw this question out there in case anyone had any ideas.  I will keep tinkering with this and update if I find a solution.

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa, which assessment is this? I thought I would try to build it and see where things are going wrong.

**Comment by chantelwetzel-noaa** [comment]
I am having this issue for the Dover sole document.  All the rmd file are in the [github repo](https://github.com/chantelwetzel-noaa/dover_sole_2021/tree/master/write_up) and a pdf from a recent build is available on the network in the Dover sole "write_up" folder.  For unknown reasons, I have ran into 'hook' issues when pushing the built pdf to github (never encountered this in the past) so unfortunately the most recent build can't be found in the repo.

**Comment by kellijohnson-NOAA** [comment]
Believe we tracked this down to the use of `\include` versus `\input` for all of the table files. See guidance [here](https://tex.stackexchange.com/questions/246/when-should-i-use-input-vs-include). Include leads to clearpage before and after the text in the file.
