### ISSUE TITLE
removing abstracts from bib file

### ISSUE THREAD

**Issue by saasem** [nwfsc-assess/sa4ss#23]
Hi- I'm working on the vermilion assessment with Melissa Monk and I'm new to GitHub and R Markdown. I can't figure out how to tell R to leave out the abstract from each bibliography entry. I'm bringing in the bib file from Mendeley (couldn't find an option to leave it out before importing). Thanks!

**Comment by kellijohnson-NOAA** [comment]
Great to hear that you are helping MM. We are happy to help provide a way forward for your bibliography, but I think we need a bit more information on what you need here. Can you provide a screen shot that maybe you mark up with what is wrong. I am thinking that the resulting Reference section in the pdf is including abstract information that you don't want to be there. If so, then we will just need to ensure there is a csl style file that is appropriate. The other option is to use grep to remove all abstract information in the .bib file.

**Comment by saasem** [comment]
Thanks! Generally there seems to be excessive information in the bib file. Hopefully the screenshots with comments are helpful. 

![Screenshot (79)](https://user-images.githubusercontent.com/80540922/117055418-5c83ff80-acd8-11eb-854a-362d0fbe7592.png)
![Screenshot (80)](https://user-images.githubusercontent.com/80540922/117055422-5db52c80-acd8-11eb-858c-f901381365cf.png)

**Comment by kellijohnson-NOAA** [comment]
Perfect, exactly the info that I was looking for. I think that this or any other auxiliary information in the .bib file is fine, we just need to implement the use of a .csl file to format the references. This isn't something I have previously put a lot of work into regarding this package, so it is not a surprise that things aren't working as good as they could be. I will mess with the formatting of the reference section and get back to you as quickly as I can.

**Comment by kellijohnson-NOAA** [comment]
@saasem Can you open sa4ss.sty in the folder that you created using draft() and play around with different types of bibliographies using the following line in that file 
[\bibliographystyle{abbrvnat}](https://github.com/nwfsc-assess/sa4ss/blob/aae821436119d81a6175ee64996b484497adc071/inst/rmarkdown/templates/sa/skeleton/sa4ss.sty#L60)
[Here](https://www.overleaf.com/learn/latex/Natbib_bibliography_styles) is some guidance on what the different styles end up looking like. Let me know how it goes and if you need more information.

**Comment by kellijohnson-NOAA** [comment]
@saasem I am curious if you have tried to build a pdf using the .bib file you have? I don't think that the abstract or file information will actually cause any harm given the current bibliography style of abbrvnat.

**Comment by saasem** [comment]
Hi- thank you! Sorry for the delay. I'm trying to figure out how to build the pdf successfully and use the right bib file. Again, I'm very new to all of this :) 
I see what you're saying though, that the rendered pdf may not show the abstracts in the bibliography. Once I'm able to get the pdf working I will let you know. Thanks again!

**Comment by kellijohnson-NOAA** [comment]
Exactly, though we might have to use sublime and ctrl+H to search and replace techreport to manual, but we can deal with that later.

**Comment by kellijohnson-NOAA** [comment]
Also referenced need for csl file in #49 so closing this issue.
