### ISSUE TITLE
add_figure caption and alt_caption terminal full stop

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/sa4ss#34]
@chantelwetzel-noaa can you remind me why we [assume that users will not put a full stop on the end of their caption or alt_caption](https://github.com/nwfsc-assess/sa4ss/blob/bdd32c7baf7e323cb20c07fdb6f78a50ee75592f/R/add_figure.R#L56)? I am sure that we talked about it and I am just forgetting. If there is not a formatting reason why the full stop is added within the function, maybe we could add a check using a function to see if the text string ends in a full stop, question mark, or exclamation mark, and if it doesn't, then add it. That way things would be back compatible for all function calls that do not have a full stop at the end of caption and alt_caption. Example code to do this would be
```
fullstop <- function(text) {
  check <- grepl("\\.$|[?!]$", text)
  out <- ifelse(check, text, paste0(text, "."))
  return(out)
}
```

**Comment by chantelwetzel-noaa** [comment]
It would make oh so very happy if you added this. When I created this function I thought hardwiring the full stop would ensure that they were included.  However, in application I have run into instances where this has been more a pain than a help.  Your proposed function is a much more clever and wise way to make sure captions are formatted correctly.

**Comment by chantelwetzel-noaa** [comment]
I cannot think of an example where we would need that.  The proposed approach would likely work for 99.9% of captions which is the best we can do.
