### ISSUE TITLE
format of bib key

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/sa4ss#36]
Thanks to @andi-stephens-NOAA for mentioning the need for formalizing bib keys. If you have ideas or concerns please respond to this issue. It would be good to get a standard practice going forward that works for all.
### Areas of concern
1. complex enough key that it works for authors that have multiple publications in a single year in the same journal
2. not so complex that it is annoying
3. doesn't violate latex rules
4. works for non-article type documents
5. clear for assessment authors that it pertains to a previous assessment for assessment documents
6. uses camel case or delimitators but not both

**Comment by andi-stephens-NOAA** [comment]
I like either:

    author_keyword_year
or
    author_year_keyword

I think the second version is a little easier to search for in a .bib file.  Camel case is just a little less clear than delimited.

**Comment by kellijohnson-NOAA** [comment]
All bib keys should be
```
Familyname:YYYY:XXX
```
where `Familyname` is the family name of the first author, `YYYY` is the year of the publication, and `XXX` are the upper-case first letters of the first three words of substance in the title. See the [documentation for biblabel](http://ftp.math.utah.edu/pub/biblabel/biblabel-0.09.html) by Nelson H. F. Beebe.
