### ISSUE TITLE
Incorrect Copyright Name on Page 2

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/sa4ss#38]
Thank you to @shcaba eagle eye for catching that Pacific Fishery Management Council by the copyright on page to was incorrect.  The template incorrectly had it as "Pacific *Fisheries* Management Council". This has been corrected in the repo via f3ae76a2854f5c7499ed7f60baba5d80c311e9fd and will be correct for any new package installs. However, if you are using a previous sa4ss version you can correct this in your document without re-installing the package.  The steps to correct this in an existing installed package area:

1. Navigate to the folder that holds your R program (e.g., C:/Program Files/R)
2. Open your current R version folder (e.g. C:/Program Files/R/R-4.0.1) then open your "library" folder.
3. Once inside the library folder open the sa4ss package and then open the following folders: library/sa4ss/rmarkdown/templates/sa/resources
4. In the resources folder there will be a single file "sadraft.tex", open this file. 
5. You can either search by the keyword "Fisheries" or navigate down to approximately line 264 where you will find the copyright command.  Change "Pacific Fisheries Management Council" to "Pacific Fishery Management Council". Save and close file.

Upon the next build of your document you should see the correction.

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa I found another one that was spelled wrong and changed them both to use glsentrylong. Then I changed the readme, description, and yaml. I think we can close this now, but I will leave that up to you.

**Comment by chantelwetzel-noaa** [comment]
Good catch on that second appearance in the citation following the copyright line.
