### ISSUE TITLE
Name of Executive Summary subheading stock biomass

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/sa4ss#39]
https://github.com/nwfsc-assess/sa4ss/blob/fcafdcfcddf89c9e6d88f6e93fee18d3bb04b9c0/inst/rmarkdown/templates/sa/skeleton/01executive.Rmd#L17

John Field mentioned that
```
Stock biomass- this section should be titled “stock biomass and dynamics” 
```

Does anyone know if his statement is __*TRUE*__? Should I change the template to read `Stock biomass and dynamics`?

**Comment by chantelwetzel-noaa** [comment]
This is TRUE.  On page [48 of the ToR](https://docs.google.com/document/d/1AluC4-pwdaXhlfCyFkC1c0YuvqyMIUzF/edit#) it provides the required sections and their names.  Looking at the required list I don't see a section called "Ecosystem Considerations" in the template. This is another required executive summary section.
