### ISSUE TITLE
Executive Summary Table & Figure Numbering

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/sa4ss#5]
The default approach is currently set to numerical (table 1 or figure 1) and needs to be updated to be changed to alphabetical (table a or figure a).  After the executive summary section the counter will need to be reset and changed to numerical numbering.

**Comment by kellijohnson-NOAA** [comment]
Thanks @chantelwetzel-noaa, this was a quick fix and should be correct now.
